*Accompanying code examples of the book "Introduction to Artificial Neural Networks and Deep Learning: A Practical Guide with Applications in Python" by Sebastian Raschka. All code examples are released under the [MIT license](https://github.com/rasbt/deep-learning-book/blob/master/LICENSE). If you find this content useful, please consider supporting the work by buying a [copy of the book](https://leanpub.com/ann-and-deeplearning).*


Other code examples and content are available on [GitHub](https://github.com/rasbt/deep-learning-book). The PDF and ebook versions of the book are available through [Leanpub](https://leanpub.com/ann-and-deeplearning).

# Appendix G - TensorFlow Basics

* [TensorFlow in a Nutshell](#TensorFlow-in-a-Nutshell)
* [Installation](#Installation)
* [Computation Graphs](#Computation-Graphs)
* [Variables](#Variables)
* [Placeholder Variables](#Placeholder-Variables)

* [CPU and GPU](#CPU-and-GPU)

In [1]:
%load_ext watermark
%watermark -a 'Sebastian Raschka' -d -p tensorflow,numpy

Sebastian Raschka 2017-02-25 

tensorflow 1.0.0
numpy 1.12.0


## TensorFlow in a Nutshell

## Installation

## Computation Graphs

In [2]:
import tensorflow as tf

g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.constant([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    col_sum = tf.reduce_sum(tf_x, axis=0)

print('tf_x:\n', tf_x)
print('\ncol_sum:\n', col_sum)

tf_x:
 Tensor("Const:0", shape=(3, 2), dtype=float32)

col_sum:
 Tensor("Sum:0", shape=(2,), dtype=float32)


In [3]:
with tf.Session(graph=g) as sess:
    mat, csum = sess.run([tf_x, col_sum])
    
print('mat:\n', mat)
print('\ncsum:\n', csum)

mat:
 [[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]]

csum:
 [  9.  12.]


In [4]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.constant([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    col_sum = tf.reduce_sum(tf_x, axis=0)
    col_sum_times_2 = col_sum * 2


with tf.Session(graph=g) as sess:
    csum_2 = sess.run(col_sum_times_2)
    
print('csum_2:\n', csum_2)

csum_2:
 [ 18.  24.]


## Variables

In [5]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    # add a constant to the matrix:
    tf_x = tf_x + x
    
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(tf_x)
    
print(result)

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [6]:
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(tf_x)
    result = sess.run(tf_x)

print(result)

[[ 2.  3.]
 [ 4.  5.]
 [ 6.  7.]]


In [7]:
g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)


with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    result = sess.run(update_tf_x)

print(result)

[[ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


## Placeholder Variables

In [8]:
import numpy as np

g = tf.Graph()

with g.as_default() as g:
    tf_x = tf.placeholder(dtype=tf.float32,
                          shape=(3, 2))

    output = tf.matmul(tf_x, tf.transpose(tf_x))


with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    np_ary = np.array([[3., 4.],
                          [5., 6.],
                          [7., 8.]])
    feed_dict = {tf_x: np_ary}
    print(sess.run(output,
                   feed_dict=feed_dict))

[[  25.   39.   53.]
 [  39.   61.   83.]
 [  53.   83.  113.]]


## Saving and Loading Variables

In [11]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)
    
    # initialize a Saver, which gets all variables
    # within this computation graph context
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    result = sess.run(update_tf_x)
    
    saver.save(sess, save_path='./my-model.ckpt')

In [12]:
with tf.Session(graph=g) as sess:
    sess.run(tf.global_variables_initializer())
    
    for epoch in range(100):
        result = sess.run(update_tf_x)
        if not epoch % 10:
            saver.save(sess, save_path='./my-model.ckpt', global_step=epoch)
    

In [15]:
g = tf.Graph()

with g.as_default() as g:
    
    tf_x = tf.Variable([[1., 2.], 
                        [3., 4.],
                        [5., 6.]], dtype=tf.float32)
    x = tf.constant(1., dtype=tf.float32)
    
    update_tf_x = tf.assign(tf_x, tf_x + x)
    
    # initialize a Saver, which gets all variables
    # within this computation graph context
    saver = tf.train.Saver()

with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model.ckpt')
    result = sess.run(update_tf_x)
    print(result)

[[ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]


In [ ]:
with tf.Session(graph=g) as sess:
    saver.restore(sess, save_path='./my-model.ckpt-90')
    result = sess.run(update_tf_x)
    print(result)

- You'll notice you still need to create the weights and bias Tensors in Python. The tf.train.Saver.restore() function loads the saved data into weights and bias.

- Since tf.train.Saver.restore() sets all the TensorFlow Variables, you don't need to call tf.global_variables_initializer().

## CPU and GPU

```python
with tf.Session() as sess:
    with tf.device("/gpu:1"):




from tensorflow.python.client import device_lib

device_lib.list_local_devices()
```